[CmdletBinding()]
param(
  [string]$NasRoot = $env:CR_NAS_DEV_ROOT,
  [string]$RepoRoot = "",
  [string]$SiteToken = $(if ($env:CR_SITE_TOKEN) { $env:CR_SITE_TOKEN } else { "dev-local-token" }),
  [int]$SitePort = 18192,
  [int]$FrontendPort = 18193,
  [int]$DaemonPort = 18191,
  [string]$SiteHost = "127.0.0.1",
  [string]$ConnectorHost = "127.0.0.1",
  [string]$FrontendUrlHost = "127.0.0.1",
  [string]$DaemonUrlHost = "",
  [string]$WorkspaceRoots = "",
  [switch]$Force
)

$ErrorActionPreference = "Stop"

function Get-RepoRoot {
  param([string]$Explicit)
  if ($Explicit) {
    return [System.IO.Path]::GetFullPath($Explicit)
  }
  $root = (& git rev-parse --show-toplevel 2>$null)
  if (-not $root) {
    throw "Could not resolve repo root. Run this script from the repository or pass -RepoRoot."
  }
  return [System.IO.Path]::GetFullPath($root.Trim())
}

function Get-FullPathNoResolve {
  param([string]$Path)
  if ([System.IO.Path]::IsPathRooted($Path)) {
    return [System.IO.Path]::GetFullPath($Path)
  }
  return [System.IO.Path]::GetFullPath((Join-Path (Get-Location) $Path))
}

function Quote-PsString {
  param([string]$Value)
  return "'" + $Value.Replace("'", "''") + "'"
}

$repo = Get-RepoRoot -Explicit $RepoRoot
if ([string]::IsNullOrWhiteSpace($NasRoot)) {
  $NasRoot = Join-Path $repo ".local-dev"
  Write-Warning "CR_NAS_DEV_ROOT is not set; using repo-local fallback: $NasRoot"
}
$root = Get-FullPathNoResolve -Path $NasRoot
if ([string]::IsNullOrWhiteSpace($DaemonUrlHost)) {
  $DaemonUrlHost = $ConnectorHost
}

$stateRoot = Join-Path $root "state"
$connectorState = Join-Path $stateRoot "connector"
$identityDir = Join-Path $stateRoot "identity"
$logsDir = Join-Path $root "logs"
$workspaceDir = Join-Path $root "workspace"
$claudeProjectsDir = Join-Path $root "claude-projects"
$tmpDir = Join-Path $root "tmp"

foreach ($dir in @($root, $stateRoot, $connectorState, $identityDir, $logsDir, $workspaceDir, $claudeProjectsDir, $tmpDir)) {
  New-Item -ItemType Directory -Force -Path $dir | Out-Null
}

$envFile = Join-Path $root "dev.env.ps1"
$siteTokenFile = Join-Path $root "site-token.txt"
$readmeFile = Join-Path $root "README.md"
$startWrapper = Join-Path $root "start-dev.ps1"
$stopWrapper = Join-Path $root "stop-dev.ps1"
$statusWrapper = Join-Path $root "status-dev.ps1"
$browserLogin = Join-Path $root "browser-login.js"

if ((Test-Path $envFile) -and -not $Force) {
  Write-Host "Keeping existing $envFile (pass -Force to rewrite)."
} else {
  $siteUrl = "http://${SiteHost}:$SitePort"
  $frontendUrl = "http://${FrontendUrlHost}:$FrontendPort"
  $daemonUrl = "http://${DaemonUrlHost}:$DaemonPort"
  $authFile = Join-Path $connectorState "auth.json"
  $stateFile = Join-Path $connectorState "daemon.json"
  $processFile = Join-Path $stateRoot "dev-processes.json"
  $workspaceRootsValue = if ([string]::IsNullOrWhiteSpace($WorkspaceRoots)) { $workspaceDir } else { $WorkspaceRoots }

  @"
# Generated by scripts/nas-dev-init.ps1. Do not commit this file.
`$env:CR_NAS_DEV_ROOT = $(Quote-PsString $root)
`$env:CR_LOCAL_DEV = '1'

# Local site backend only.
`$env:CR_SITE_HOST = $(Quote-PsString $SiteHost)
`$env:CR_SITE_PORT = '$SitePort'
`$env:CR_SITE_TOKEN = $(Quote-PsString $SiteToken)
`$env:CR_SITE_TOKEN_FILE = $(Quote-PsString $siteTokenFile)
`$env:CR_SITE_AUTH_OPTIONAL = '0'
`$env:CR_SITE_USAGE_DISABLED = '1'
`$env:CR_SITE_BACKEND_URL = $(Quote-PsString $siteUrl)

# Local connector daemon. State is isolated from the user's normal connector.
`$env:CR_CONNECTOR_HOST = $(Quote-PsString $ConnectorHost)
`$env:CR_CONNECTOR_PORT = '$DaemonPort'
`$env:CR_CONNECTOR_STATE_DIR = $(Quote-PsString $connectorState)
`$env:CR_CONNECTOR_STATE_FILE = $(Quote-PsString $stateFile)
`$env:CR_CONNECTOR_AUTH_FILE = $(Quote-PsString $authFile)
`$env:CR_IDENTITY_DIR = $(Quote-PsString $identityDir)
`$env:CR_CONNECTOR_WORKSPACE_ROOTS = $(Quote-PsString $workspaceRootsValue)
`$env:CR_CONNECTOR_DISABLE_AUTOLOAD = '0'

# Convenience values used by scripts and manual debugging.
`$env:CR_DEV_FRONTEND_URL = $(Quote-PsString $frontendUrl)
`$env:CR_DEV_SITE_URL = $(Quote-PsString $siteUrl)
`$env:CR_DEV_DAEMON_URL = $(Quote-PsString $daemonUrl)
`$env:CR_DEV_PROCESS_FILE = $(Quote-PsString $processFile)
`$env:CR_DEV_LOG_DIR = $(Quote-PsString $logsDir)
`$env:CR_DEV_WORKSPACE_DIR = $(Quote-PsString $workspaceDir)
`$env:CR_DEV_CLAUDE_PROJECTS_DIR = $(Quote-PsString $claudeProjectsDir)

# Keep temporary files away from the production profile while testing.
`$env:TEMP = $(Quote-PsString $tmpDir)
`$env:TMP = $(Quote-PsString $tmpDir)
"@ | Set-Content -Encoding utf8 -Path $envFile
  $SiteToken | Set-Content -Encoding utf8 -Path $siteTokenFile
}

@"
# DeskRelay Local Dev Root

This folder is a local-dev runtime root. It is safe to put it on a NAS share.
It keeps local dev state isolated from the user's normal connector.

## Start

From the repository:

~~~powershell
.\scripts\dev-local-start.ps1 -NasRoot "$root"
~~~

Open:

~~~text
http://127.0.0.1:$FrontendPort
~~~

Token login:

~~~text
$SiteToken
~~~

Token file:

~~~text
$siteTokenFile
~~~

If the app is already open, paste the contents of browser-login.js into the browser console once.

## Stop

~~~powershell
.\scripts\dev-local-stop.ps1 -NasRoot "$root"
~~~

## What stays local

- site backend runs on `127.0.0.1:$SitePort`
- frontend dev server runs on `127.0.0.1:$FrontendPort`
- connector daemon runs on `127.0.0.1:$DaemonPort`
- connector state, auth, identity, logs, and workspace roots live under this folder
- no hosted deploy
- no hosted backend calls
- no normal connector state is touched
"@ | Set-Content -Encoding utf8 -Path $readmeFile

@"
localStorage.setItem("cr.site-token", "$SiteToken");
localStorage.removeItem("cr.site-base-url");
location.reload();
"@ | Set-Content -Encoding utf8 -Path $browserLogin

@"
param([switch]`$NoFrontend, [switch]`$NoDaemon, [switch]`$NoRegisterDevice)
& $(Quote-PsString (Join-Path $repo "scripts\dev-local-start.ps1")) -NasRoot $(Quote-PsString $root) -NoFrontend:`$NoFrontend -NoDaemon:`$NoDaemon -NoRegisterDevice:`$NoRegisterDevice
"@ | Set-Content -Encoding utf8 -Path $startWrapper

@"
& $(Quote-PsString (Join-Path $repo "scripts\dev-local-stop.ps1")) -NasRoot $(Quote-PsString $root)
"@ | Set-Content -Encoding utf8 -Path $stopWrapper

@"
& $(Quote-PsString (Join-Path $repo "scripts\dev-local-status.ps1")) -NasRoot $(Quote-PsString $root)
"@ | Set-Content -Encoding utf8 -Path $statusWrapper

Write-Host "Local dev root ready: $root"
Write-Host "Env file: $envFile"
Write-Host "Start: .\scripts\dev-local-start.ps1 -NasRoot `"$root`""
